version: "3.1"
services:

    www:
        build: .
        container_name: lamp
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini

volumes:
    persistent:
